<?php
namespace Amisure\P4SApiBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\NoResultException;

/**
 * EvaluationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvaluationModelRepository extends EntityRepository
{
	public function getAvailableCodes()
	{
		$q = $this->createQueryBuilder('e')
			->select('DISTINCT e.code')
			->getQuery();
		$data = $q->getScalarResult();
		return $data;
	}
}
