parameters:
    p4s_host: %p4s_path%/api
    accessor.mocked.class: Amisure\P4SApiBundle\Service\MockedDataAccessor
    accessor.dbmocked.class: Amisure\P4SApiBundle\Service\DbMockedDataAccessor
    accessor.class: Amisure\P4SApiBundle\Service\MockedDataAccessor

services:
    p4s.accessor:
        class: %accessor.dbmocked.class%
        arguments: [@doctrine.orm.entity_manager, @session, @security.context, %p4s_host%]
        tags:
            -  { name: twig.extension }
            
    p4s.paramconverter.user:
        class: Amisure\P4SApiBundle\ParamConverter\UserParamConverter
        arguments: [@p4s.accessor]
        tags:
            - { name: request.param_converter, priority: 20 }
            
    hwi_oauth.user.provider.entity:
        class: HWI\Bundle\OAuthBundle\Security\Core\User\OAuthUserProvider
    ib_user.oauth_user_provider:
        class: Amisure\P4SApiBundle\OAuth\UserProvider
        arguments: [@session, @doctrine, @service_container]
